// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsrbalvyocpsrinzlaxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzcmJhbHZ5b2Nwc3JpbnpsYXhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5NjczMzQsImV4cCI6MjA4NjU0MzMzNH0.TTKUuf8trrY_51F1LV_a3evkEKf3QUfJORpH4Dwpgp0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});